package jp.kaiz.rtmx.generator

import java.io.File
import java.lang.reflect.GenericArrayType
import java.lang.reflect.ParameterizedType
import java.lang.reflect.Type
import java.lang.reflect.TypeVariable
import java.lang.reflect.WildcardType

object DtsEmitter {
    // TSでは予約語をIdentifierとして使えないため、末尾にアンダースコアを付与して回避する
    private val TS_RESERVED = setOf(
        "break", "case", "catch", "class", "const", "continue", "debugger",
        "default", "delete", "do", "else", "enum", "export", "extends",
        "false", "finally", "for", "function", "if", "import", "in",
        "instanceof", "new", "null", "return", "super", "switch", "this",
        "throw", "true", "try", "typeof", "var", "void", "while", "with",
        "as", "implements", "interface", "let", "package", "private",
        "protected", "public", "static", "yield"
    )

    private fun sanitizeSegment(s: String) = if (s in TS_RESERVED) "${s}_" else s

    // "java.util.function" → "java.util.function_"
    private fun pkgToNs(pkg: String) = pkg.split('.').joinToString(".") { sanitizeSegment(it) }

    fun emit(classes: List<JavaClass>, outputDir: File) {
        outputDir.mkdirs()
        val byPackage = classes.groupBy { it.fqn.substringBeforeLast('.') }
        val byFqn = classes.associateBy { it.fqn }

        for ((pkg, pkgClasses) in byPackage) {
            val ns = pkgToNs(pkg)
            val sb = StringBuilder()

            sb.appendLine("// DO NOT EDIT!! This file is generated by rtmx. Any changes will be lost.")

            // Namespace block — holds actual class declarations with real extends chains
            sb.appendLine("declare namespace $ns {")
            for (cls in pkgClasses) {
                emitNsClass(cls, sb, byFqn)
            }
            sb.appendLine("}")
            sb.appendLine()

            // Module block — re-exports everything so user imports work
            sb.appendLine("declare module \"$pkg\" {")
            for (cls in pkgClasses) {
                val simpleName = cls.fqn.substringAfterLast('.')
                sb.appendLine("  export import $simpleName = $ns.$simpleName;")
            }
            sb.appendLine("}")

            File(outputDir, pkg.replace('.', '_') + ".d.ts").writeText(sb.toString())
        }
    }

    private fun emitNsClass(cls: JavaClass, sb: StringBuilder, byFqn: Map<String, JavaClass>) {
        val simpleName = cls.fqn.substringAfterLast('.')

        val typeParamsStr = cls.typeParams
            .takeIf { it.isNotEmpty() }
            ?.joinToString(", ", "<", ">") { tp ->
                val bounds = tp.upperBounds.filter { it != java.lang.Object::class.java }
                if (bounds.isEmpty()) "${tp.name} = any"
                else "${tp.name} extends ${bounds.joinToString(" & ") { typeToTs(it) }} = any"
            } ?: ""

        if (cls.isInterface) {
            val extendsClause = cls.superInterfaces
                .takeIf { it.isNotEmpty() }
                ?.joinToString(", ", " extends ") { typeToTs(it) } ?: ""

            sb.appendLine("  interface $simpleName$typeParamsStr$extendsClause {")
            for (f in cls.fields.filterNot { it.isStatic }) {
                sb.appendLine("    ${f.name}: ${typeToTs(f.javaType)};")
            }
            for (m in cls.methods.filterNot { it.isStatic }) {
                val params = buildParams(m.paramTypes, m.isVarArgs)
                sb.appendLine("    ${m.name}($params): ${typeToTs(m.returnType)};")
            }
            sb.appendLine("  }")

            val staticFields = cls.fields.filter { it.isStatic }
            val staticMethods = cls.methods.filter { it.isStatic }
            if (staticFields.isNotEmpty() || staticMethods.isNotEmpty()) {
                sb.appendLine("  namespace $simpleName {")
                for (f in staticFields) {
                    sb.appendLine("    const ${f.name}: ${typeToTs(f.javaType)};")
                }
                for (m in staticMethods) {
                    val params = buildParams(m.paramTypes, m.isVarArgs)
                    sb.appendLine("    function ${m.name}($params): ${typeToTs(m.returnType)};")
                }
                sb.appendLine("  }")
            }
            return
        }

        val extendsClause = cls.superclass?.let { " extends ${typeToTs(it)}" } ?: ""
        val abstractModifier = if (cls.isAbstract) "abstract " else ""
        val implementsClause = cls.superInterfaces
            .takeIf { it.isNotEmpty() }
            ?.joinToString(", ", " implements ") { typeToTs(it) } ?: ""

        sb.appendLine("  ${abstractModifier}class $simpleName$typeParamsStr$extendsClause$implementsClause {")
        val emittedInstanceMethods = mutableSetOf<String>()

        for (ctor in cls.constructors) {
            val params = buildParams(ctor.paramTypes, ctor.isVarArgs)
            sb.appendLine("    constructor($params);")
        }
        for (f in cls.fields) {
            val static = if (f.isStatic) "static " else ""
            sb.appendLine("    ${static}${f.name}: ${typeToTs(f.javaType)};")
        }
        for (m in cls.methods) {
            val static = if (m.isStatic) "static " else ""
            val override = if (!m.isStatic && overridesSuperclassMethod(cls, m, byFqn)) "override " else ""
            val params = buildParams(m.paramTypes, m.isVarArgs)
            sb.appendLine("    ${static}${override}${m.name}($params): ${typeToTs(m.returnType)};")
            if (!m.isStatic) emittedInstanceMethods.add(methodKey(m))
        }

        if (cls.isAbstract) {
            for (iface in collectInterfaces(cls.superInterfaces, byFqn)) {
                for (m in iface.methods.filterNot { it.isStatic }) {
                    if (emittedInstanceMethods.add(methodKey(m))) {
                        val params = buildParams(m.paramTypes, m.isVarArgs)
                        sb.appendLine("    abstract ${m.name}($params): ${typeToTs(m.returnType)};")
                    }
                }
            }
        }

        sb.appendLine("  }")
    }

    private fun fqnToNsRef(fqn: String): String {
        val pkg = fqn.substringBeforeLast('.')
        val name = fqn.substringAfterLast('.')
        return "${pkgToNs(pkg)}.$name"
    }

    private fun buildParams(paramTypes: List<Type>, isVarArgs: Boolean): String {
        if (paramTypes.isEmpty()) return ""
        return paramTypes.mapIndexed { i, t ->
            if (isVarArgs && i == paramTypes.lastIndex) {
                val elemType = when (t) {
                    is GenericArrayType -> typeToTs(t.genericComponentType)
                    is Class<*> -> typeToTs(t.componentType ?: t)
                    else -> typeToTs(t)
                }
                "...p$i: $elemType[]"
            } else {
                "p$i: ${typeToTs(t)}"
            }
        }.joinToString(", ")
    }

    private fun collectInterfaces(types: List<Type>, byFqn: Map<String, JavaClass>): List<JavaClass> {
        val result = mutableListOf<JavaClass>()
        val seen = mutableSetOf<String>()

        fun visit(type: Type) {
            val iface = rawClassName(type)?.let(byFqn::get) ?: return
            if (!iface.isInterface || !seen.add(iface.fqn)) return
            result.add(iface)
            iface.superInterfaces.forEach(::visit)
        }

        types.forEach(::visit)
        return result
    }

    private fun overridesSuperclassMethod(
        cls: JavaClass,
        method: JavaMethod,
        byFqn: Map<String, JavaClass>
    ): Boolean {
        val key = methodSignatureKey(method)

        fun visit(type: Type?): Boolean {
            val superClass = type?.let(::rawClassName)?.let(byFqn::get) ?: return false
            if (superClass.methods.any { !it.isStatic && methodSignatureKey(it) == key }) return true
            return visit(superClass.superclass)
        }

        return visit(cls.superclass)
    }

    private fun rawClassName(type: Type): String? = when (type) {
        is Class<*> -> type.name
        is ParameterizedType -> (type.rawType as? Class<*>)?.name
        else -> null
    }

    private fun methodKey(method: JavaMethod): String =
        "${method.name}(${method.paramTypes.joinToString(",") { typeToTs(it) }}):${typeToTs(method.returnType)}"

    private fun methodSignatureKey(method: JavaMethod): String =
        "${method.name}(${method.paramTypes.joinToString(",") { rawTypeKey(it) }})"

    private fun rawTypeKey(type: Type): String = when (type) {
        is Class<*> -> type.name
        is ParameterizedType -> (type.rawType as? Class<*>)?.name ?: type.typeName
        is GenericArrayType -> "${rawTypeKey(type.genericComponentType)}[]"
        else -> type.typeName
    }

    internal fun typeToTs(type: Type): String {
        return when (type) {
            is Class<*> -> classToTs(type)
            is ParameterizedType -> {
                val raw = type.rawType as? Class<*> ?: return "any"
                val rawRef = classToTs(raw)
                if (rawRef in PRIMITIVE_TS_TYPES) rawRef
                else {
                    val args = type.actualTypeArguments.map { typeToTs(it) }
                    "$rawRef<${args.joinToString(", ")}>"
                }
            }
            is TypeVariable<*> -> type.name
            is WildcardType -> {
                val upper = type.upperBounds.firstOrNull()
                if (upper != null && upper != java.lang.Object::class.java) typeToTs(upper)
                else "any"
            }
            is GenericArrayType -> "${typeToTs(type.genericComponentType)}[]"
            else -> "any"
        }
    }

    private fun classToTs(cls: Class<*>): String {
        if (cls.isPrimitive) return when (cls) {
            java.lang.Integer.TYPE, java.lang.Long.TYPE, java.lang.Float.TYPE,
            java.lang.Double.TYPE, java.lang.Short.TYPE, java.lang.Byte.TYPE -> "number"
            java.lang.Boolean.TYPE -> "boolean"
            java.lang.Character.TYPE -> "string"
            java.lang.Void.TYPE -> "void"
            else -> "any"
        }
        if (cls.isArray) return "${typeToTs(cls.componentType)}[]"
        return when (cls) {
            java.lang.String::class.java, java.lang.CharSequence::class.java -> "string"
            java.lang.Boolean::class.java -> "boolean"
            java.lang.Integer::class.java, java.lang.Long::class.java,
            java.lang.Float::class.java, java.lang.Double::class.java,
            java.lang.Short::class.java, java.lang.Byte::class.java,
            java.lang.Number::class.java -> "number"
            java.lang.Character::class.java -> "string"
            java.lang.Void::class.java -> "void"
            java.lang.Object::class.java -> "any"
            else -> {
                val fqn = cls.name
                if (fqn.contains('$')) return "any"
                fqnToNsRef(fqn)
            }
        }
    }

    private val PRIMITIVE_TS_TYPES = setOf("any", "string", "number", "boolean", "void")
}
