package jp.kaiz.rtmx.generator

import java.io.File

object DtsEmitter {
    private fun pkgToNs(pkg: String) = pkg

    fun emit(classes: List<JavaClass>, outputDir: File) {
        outputDir.mkdirs()
        val byPackage = classes.groupBy { it.fqn.substringBeforeLast('.') }

        for ((pkg, pkgClasses) in byPackage) {
            val ns = pkgToNs(pkg)
            val sb = StringBuilder()

            sb.appendLine("// DO NOT EDIT!! This file is generated by rtmx. Any changes will be lost.")

            // Namespace block — holds actual class declarations with real extends chains
            sb.appendLine("declare namespace $ns {")
            for (cls in pkgClasses) {
                emitNsClass(cls, sb)
            }
            sb.appendLine("}")
            sb.appendLine()

            // Module block — re-exports everything so user imports work
            sb.appendLine("declare module \"$pkg\" {")
            for (cls in pkgClasses) {
                val simpleName = cls.fqn.substringAfterLast('.')
                sb.appendLine("  export import $simpleName = $ns.$simpleName;")
            }
            sb.appendLine("}")

            File(outputDir, pkg.replace('.', '_') + ".d.ts").writeText(sb.toString())
        }
    }

    private fun emitNsClass(cls: JavaClass, sb: StringBuilder) {
        val simpleName = cls.fqn.substringAfterLast('.')
        val extendsClause = cls.superclass?.let { " extends ${fqnToNsRef(it)}" } ?: ""
        val implementsClause = cls.superInterfaces
            .takeIf { it.isNotEmpty() }
            ?.joinToString(", ", " implements ") { fqnToNsRef(it) } ?: ""

        sb.appendLine("  class $simpleName$extendsClause$implementsClause {")

        for (ctor in cls.constructors) {
            val params = buildParams(ctor.paramTypes, ctor.isVarArgs)
            sb.appendLine("    constructor($params);")
        }
        for (f in cls.fields) {
            val static = if (f.isStatic) "static " else ""
            sb.appendLine("    ${static}${f.name}: ${classToTs(f.javaType)};")
        }
        for (m in cls.methods) {
            val static = if (m.isStatic) "static " else ""
            val params = buildParams(m.paramTypes, m.isVarArgs)
            sb.appendLine("    ${static}${m.name}($params): ${classToTs(m.returnType)};")
        }

        sb.appendLine("  }")
    }

    private fun fqnToNsRef(fqn: String): String {
        val pkg = fqn.substringBeforeLast('.')
        val name = fqn.substringAfterLast('.')
        return "${pkgToNs(pkg)}.$name"
    }

    private fun buildParams(paramTypes: List<Class<*>>, isVarArgs: Boolean): String {
        if (paramTypes.isEmpty()) return ""
        return paramTypes.mapIndexed { i, t ->
            if (isVarArgs && i == paramTypes.lastIndex) {
                "...p$i: ${classToTs(t.componentType ?: t)}[]"
            } else {
                "p$i: ${classToTs(t)}"
            }
        }.joinToString(", ")
    }

    private fun classToTs(cls: Class<*>): String {
        if (cls.isPrimitive) return when (cls) {
            java.lang.Integer.TYPE, java.lang.Long.TYPE, java.lang.Float.TYPE,
            java.lang.Double.TYPE, java.lang.Short.TYPE, java.lang.Byte.TYPE -> "number"
            java.lang.Boolean.TYPE -> "boolean"
            java.lang.Character.TYPE -> "string"
            java.lang.Void.TYPE -> "void"
            else -> "any"
        }
        if (cls.isArray) {
            val elem = cls.componentType
            return if (!elem.isArray) "${classToTs(elem)}[]" else "any[]"
        }
        return when (cls) {
            java.lang.String::class.java, java.lang.CharSequence::class.java -> "string"
            java.lang.Boolean::class.java -> "boolean"
            java.lang.Integer::class.java, java.lang.Long::class.java,
            java.lang.Float::class.java, java.lang.Double::class.java,
            java.lang.Short::class.java, java.lang.Byte::class.java,
            java.lang.Number::class.java -> "number"
            java.lang.Character::class.java -> "string"
            java.lang.Void::class.java -> "void"
            java.lang.Object::class.java -> "any"
            else -> {
                val fqn = cls.name
                if (fqn.contains('$')) return "any"
                fqnToNsRef(fqn)
            }
        }
    }
}
